# .github/workflows/pin_scanner_ci.yml

name: PIN Scanner CI

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r requirements.txt

      - name: 4. Restore Logs Cache
        uses: actions/cache@v4
        id: cache-state
        with:
          # We only cache the log files now. The progress file is gone.
          path: |
            found_pins.log
            potential_pins.log
          key: ${{ runner.os }}-pincache-${{ github.ref }}

      - name: 5. Run the PIN Scanner Script
        env:
          END_PIN: 1000
        run: python pin_scanner.py

      # Step 6 (Check for new content and send Telegram notification) remains exactly the same
      - name: 6. Check for new content and send Telegram notification
        run: |
          if [[ ! -f new_find_content.txt ]]; then
            echo "No new high-priority content found to notify."
          else
            echo "New content found! Preparing Telegram notification."
            MESSAGE_CONTENT=$(cat new_find_content.txt)
            MESSAGE="🚨 *New Exam Content Found!*\n\n\`\`\`\n${MESSAGE_CONTENT}\n\`\`\`"
            curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
                "text": "'"$MESSAGE"'",
                "parse_mode": "Markdown"
            }'
            echo "Telegram notification sent."
          fi